apiVersion: v1
kind: ConfigMap
metadata:
  name: prayingtymes-telegrambot-config
  labels:
    app: prayingtymes-telegrambot
data:
  java_options: "-Dspring.config.location=classpath:/application.yml -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0"
  timeskeeper_url: "http://localhost:8080"
