apiVersion: apps/v1
kind: Deployment
metadata:
  name: prayingtimes-telegrambot-deployment
  labels:
    app: prayingtimes-telegrambot
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prayingtimes-telegrambot
  template:
    metadata:
      labels:
        app: prayingtimes-telegrambot
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: JDK_JAVA_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: prayingtymes-telegrambot-config
                  key: java_options
            - name: TIMESKEEPER_URL
              valueFrom:
                configMapKeyRef:
                  name: prayingtymes-telegrambot-config
                  key: timeskeeper_url
            - name: BOT_NAME
              valueFrom:
                secretKeyRef:
                  name: prayingtymes-telegrambot-secret
                  key: bot_name
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prayingtymes-telegrambot-secret
                  key: bot_token