kind: Secret
apiVersion: v1
metadata:
  name: prayingtymes-telegrambot-secret
  labels:
    app: prayingtymes-telegrambot
type: Opaque
data:
  bot_name: {{ default "" .Values.botName | b64enc | quote }}
  bot_token: {{ default "" .Values.botToken | b64enc | quote }}
